# Generated by Django 3.2.22 on 2023-10-25 11:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Booking_App', '0004_auto_20231025_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='booking',
            name='meals_desired',
            field=models.CharField(choices=[('CHARBURGER WITH CHEESE', 'CHARBURGER WITH CHEESE'), ('CHARBURGER', 'CHARBURGER'), ('DOUBLE CHAR WITH CHEESE', 'DOUBLE CHAR WITH CHEESE'), ('BBQ CHAR WITH CHEESE', 'BBQ CHAR WITH CHEESE'), ('PORTABELLA CHAR', 'PORTABELLA CHAR'), ('TERIYAKI CHAR', 'TERIYAKI CHAR'), ('GRILLED CHICKEN-WICH', 'GRILLED CHICKEN-WICH'), ('SPICY CRISPY CHICKEN', 'SPICY CRISPY CHICKEN'), ('CHICKEN CLUB', 'CHICKEN CLUB'), ('AHI TUNA FILET', 'AHI TUNA FILET'), ('VEGGIE BURGER', 'VEGGIE BURGER'), ('VEGGIE CHEESE BURGER', 'VEGGIE CHEESE BURGER'), ('CHICKEN CAESAR', 'CHICKEN CAESAR'), ('GARDEN SALAD', 'GARDEN SALAD'), ('10 PCS CRISPY', '10 PCS CRISPY'), ('FRENCH FRIES', 'FRENCH FRIES'), ('ONION RINGS', 'ONION RINGS')], default='CHARBURGER', max_length=80),
        ),
    ]
