# Generated by Django 3.2.22 on 2023-10-25 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking_App', '0006_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
