# Generated by Django 3.2.22 on 2023-10-27 08:51

import Booking_App.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Booking_App', '0008_booking_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(default='085 123 3434', max_length=15)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('booking_date', models.DateTimeField(default=Booking_App.models.get_current_date)),
                ('meals_desired', models.CharField(choices=[('CHARBURGER WITH CHEESE', 'CHARBURGER WITH CHEESE'), ('CHARBURGER', 'CHARBURGER'), ('DOUBLE CHAR WITH CHEESE', 'DOUBLE CHAR WITH CHEESE'), ('BBQ CHAR WITH CHEESE', 'BBQ CHAR WITH CHEESE'), ('PORTABELLA CHAR', 'PORTABELLA CHAR'), ('TERIYAKI CHAR', 'TERIYAKI CHAR'), ('GRILLED CHICKEN-WICH', 'GRILLED CHICKEN-WICH'), ('SPICY CRISPY CHICKEN', 'SPICY CRISPY CHICKEN'), ('CHICKEN CLUB', 'CHICKEN CLUB'), ('AHI TUNA FILET', 'AHI TUNA FILET'), ('VEGGIE BURGER', 'VEGGIE BURGER'), ('VEGGIE CHEESE BURGER', 'VEGGIE CHEESE BURGER'), ('CHICKEN CAESAR', 'CHICKEN CAESAR'), ('GARDEN SALAD', 'GARDEN SALAD'), ('10 PCS CRISPY', '10 PCS CRISPY'), ('FRENCH FRIES', 'FRENCH FRIES'), ('ONION RINGS', 'ONION RINGS')], default='CHARBURGER', max_length=80)),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('additional_meal', models.ManyToManyField(blank=True, to='Booking_App.Meal')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
