# Generated by Django 3.2.22 on 2023-10-27 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking_App', '0009_delivery_meal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='meals_desired',
        ),
    ]
