# Generated by Django 3.2.22 on 2023-10-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking_App', '0011_auto_20231027_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='meals_desired',
        ),
        migrations.AddField(
            model_name='delivery',
            name='meals_desired',
            field=models.ManyToManyField(blank=True, to='Booking_App.Meal'),
        ),
    ]
